apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-infotrygd-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/config/infotrygd_hjq-user/jdbc_url
        mountPath: /oracle/infotrygd_hj/jdbc_url
      - kvPath: /oracle/data/dev/creds/infotrygd_hjq-user/username
        mountPath: /oracle/infotrygd_hj/username
      - kvPath: /oracle/data/dev/creds/infotrygd_hjq-user/password
        mountPath: /oracle/infotrygd_hj/password