apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-infotrygd-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  secureLogs:
    enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/infotrygd_hjq-user
        mountPath: /secrets/infotrygd_hj/credentials
      - kvPath: oracle/data/dev/config/infotrygd_hjq
        mountPath: /secrets/infotrygd_hj/config
  ingresses:
    - https://hm-infotrygd-proxy.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-infotrygd-poller
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: dev-gcp
        - application: hm-bestillingsordning-river
          namespace: teamdigihot
          cluster: dev-gcp