CREATE TABLE SA_SAK_10
(
    S01_PERSONKEY          NUMBER(15)                                  NOT NULL,
    S05_SAKSBLOKK          CHAR(1 CHAR)                                NOT NULL,
    S10_SAKSNR             CHAR(2 CHAR)                                NOT NULL,
    S10_REG_DATO           NUMBER(8)                                   NOT NULL,
    S10_MOTTATTDATO        NUMBER(8)                                   NOT NULL,
    S10_KAPITTELNR         CHAR(2 CHAR)                                NOT NULL,
    S10_VALG               CHAR(2 CHAR)                                NOT NULL,
    S10_UNDERVALG          CHAR(2 CHAR)                                NOT NULL,
    S10_DUBLETT_FEIL       CHAR(1 CHAR)                                NOT NULL,
    S10_TYPE               CHAR(2 CHAR)                                NOT NULL,
    S10_INNSTILLING        CHAR(2 CHAR)                                NOT NULL,
    S10_RESULTAT           CHAR(2 CHAR)                                NOT NULL,
    S10_NIVAA              VARCHAR2(3 CHAR)                            NOT NULL,
    S10_INNSTILLDATO       NUMBER(8)                                   NOT NULL,
    S10_VEDTAKSDATO        NUMBER(8)                                   NOT NULL,
    S10_IVERKSATTDATO      NUMBER(8)                                   NOT NULL,
    S10_GRUNNBL_DATO       NUMBER(8)                                   NOT NULL,
    S10_AARSAKSKODE        CHAR(2 CHAR)                                NOT NULL,
    S10_TELLEPUNKT         VARCHAR2(3 CHAR)                            NOT NULL,
    S10_TELLETYPE          CHAR(1 CHAR)                                NOT NULL,
    S10_TELLEDATO          NUMBER(8)                                   NOT NULL,
    S10_EVAL_KODE          VARCHAR2(4 CHAR)                            NOT NULL,
    S10_EVAL_TIR           CHAR(1 CHAR)                                NOT NULL,
    S10_FREMLEGG           VARCHAR2(3 CHAR)                            NOT NULL,
    S10_INNSTILLING2       CHAR(2 CHAR)                                NOT NULL,
    S10_INNSTILLDATO2      NUMBER(8)                                   NOT NULL,
    S10_ANNEN_INSTANS      CHAR(1 CHAR)                                NOT NULL,
    S10_BEHEN_TYPE         VARCHAR2(3 CHAR)                            NOT NULL,
    S10_BEHEN_ENHET        VARCHAR2(4 CHAR)                            NOT NULL,
    S10_REG_AV_TYPE        VARCHAR2(3 CHAR)                            NOT NULL,
    S10_REG_AV_ENHET       VARCHAR2(4 CHAR)                            NOT NULL,
    S10_DIFF_FRAMLEGG      VARCHAR2(3 CHAR)                            NOT NULL,
    S10_INNSTILLT_AV_TYPE  VARCHAR2(3 CHAR)                            NOT NULL,
    S10_INNSTILLT_AV_ENHET VARCHAR2(4 CHAR)                            NOT NULL,
    S10_VEDTATT_AV_TYPE    VARCHAR2(3 CHAR)                            NOT NULL,
    S10_VEDTATT_AV_ENHET   VARCHAR2(4 CHAR)                            NOT NULL,
    S10_PRIO_TAB           VARCHAR2(6 CHAR)                            NOT NULL,
    S10_AOE                VARCHAR2(3 CHAR)                            NOT NULL,
    S10_ES_SYSTEM          CHAR(1 CHAR)                                NOT NULL,
    S10_ES_GSAK_OPPDRAGSID NUMBER(10)                                  NOT NULL,
    S10_KNYTTET_TIL_SAK    CHAR(2 CHAR)                                NOT NULL,
    S10_VEDTAKSTYPE        CHAR(1 CHAR)                                NOT NULL,
    S10_REELL_ENHET        VARCHAR2(4 CHAR)                            NOT NULL,
    S10_MOD_ENDRET         CHAR(1 CHAR)                                NOT NULL,
    TK_NR                  VARCHAR2(4)                                 NOT NULL,
    F_NR                   VARCHAR2(11)                                NOT NULL,
    OPPRETTET              TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_I_KILDE         TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    KILDE_IS               VARCHAR2(12 CHAR) DEFAULT ' '               NOT NULL,
    REGION                 CHAR(1 CHAR)      DEFAULT ' '               NOT NULL,
    ID_SAK                 NUMBER                                      NOT NULL
        CONSTRAINT PK_SA_SAK
            PRIMARY KEY,
    OPPDATERT              TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DB_SPLITT              CHAR(2 CHAR)      DEFAULT '99'              NOT NULL
);

CREATE TABLE SA_SAKSBLOKK_05
(
    S01_PERSONKEY    NUMBER(15)                                  NOT NULL,
    S05_SAKSBLOKK    CHAR(1 CHAR)                                NOT NULL,
    S05_GRUPPE       CHAR(2 CHAR)                                NOT NULL,
    S05_BRUKERID     VARCHAR2(7 CHAR)                            NOT NULL,
    S05_MENGDETELLET CHAR(1 CHAR)                                NOT NULL,
    TK_NR            VARCHAR2(4)                                 NOT NULL,
    F_NR             VARCHAR2(11)                                NOT NULL,
    OPPRETTET        TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_I_KILDE   TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    KILDE_IS         VARCHAR2(12 CHAR) DEFAULT ' '               NOT NULL,
    REGION           CHAR(1 CHAR)      DEFAULT ' '               NOT NULL,
    ID_SBLK          NUMBER                                      NOT NULL
        CONSTRAINT PK_SA_SAKSBLOKK
            PRIMARY KEY,
    OPPDATERT        TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DB_SPLITT        CHAR(2 CHAR)      DEFAULT '99'              NOT NULL
);

CREATE TABLE INFOTRYGD_HJQ.SA_HENDELSE_20
(
    S01_PERSONKEY       NUMBER(15)                                   NOT NULL,
    S05_SAKSBLOKK       CHAR(1 CHAR)                                 NOT NULL,
    S20_AKSJONSDATO_SEQ NUMBER(8)                                    NOT NULL,
    S20_S_B_KODE        CHAR(1 CHAR)                                 NOT NULL,
    S20_BREVNUMMER      CHAR(2 CHAR)                                 NOT NULL,
    S20_MOTTAKERKODE    VARCHAR2(3 CHAR)                             NOT NULL,
    S20_MOTTAKERNR      VARCHAR2(11 CHAR)                            NOT NULL,
    S20_FNR_ANR_INSTNR  NUMBER(11)                                   NOT NULL,
    S20_OPPLYSNING      VARCHAR2(38 CHAR)                            NOT NULL,
    S20_ANT_PURREUKER_1 CHAR(2 CHAR)                                 NOT NULL,
    S20_ANT_PURREUKER_2 CHAR(2 CHAR)                                 NOT NULL,
    S20_ANT_PURREUKER_3 CHAR(2 CHAR)                                 NOT NULL,
    S20_S_PURRENR       CHAR(1 CHAR)                                 NOT NULL,
    S20_1_PURREDATO     NUMBER(8)                                    NOT NULL,
    S20_2_PURREDATO     NUMBER(8)                                    NOT NULL,
    S20_3_PURREDATO     NUMBER(8)                                    NOT NULL,
    S20_RETURDATO       NUMBER(8)                                    NOT NULL,
    S20_NESTE_PURREDATO NUMBER(8)                                    NOT NULL,
    S20_SAKSNR          CHAR(2 CHAR)                                 NOT NULL,
    S20_KLADD           CHAR(1 CHAR)                                 NOT NULL,
    S20_LOPENR_FM01     CHAR(1 CHAR)                                 NOT NULL,
    S20_LOPENR_PRINT    VARCHAR2(3 CHAR)                             NOT NULL,
    S20_SENTRALPRINT    CHAR(1 CHAR)                                 NOT NULL,
    S20_BREVTYPE        CHAR(1 CHAR)                                 NOT NULL,
    S20_TEKSTKODE_1     VARCHAR2(4 CHAR)                             NOT NULL,
    S20_TEKSTKODE_2     VARCHAR2(4 CHAR)                             NOT NULL,
    S20_TEKSTKODE_3     VARCHAR2(4 CHAR)                             NOT NULL,
    S20_TEKSTKODE_4     VARCHAR2(4 CHAR)                             NOT NULL,
    S20_TEKSTKODE_5     VARCHAR2(4 CHAR)                             NOT NULL,
    S20_PURRETEKST_1    VARCHAR2(4 CHAR)                             NOT NULL,
    S20_PURRETEKST_2    VARCHAR2(4 CHAR)                             NOT NULL,
    S20_PURRETEKST_3    VARCHAR2(4 CHAR)                             NOT NULL,
    S20_DATO_DANNET     NUMBER(8)                                    NOT NULL,
    S20_LAGER           CHAR(1 CHAR)                                 NOT NULL,
    S20_REG_AV          VARCHAR2(3 CHAR)                             NOT NULL,
    S20_OPPR_TKNR       VARCHAR2(4 CHAR)                             NOT NULL,
    S20_OPPR_BRUKERID   VARCHAR2(7 CHAR)                             NOT NULL,
    S20_IKKE_AVBRYT     CHAR(1 CHAR)                                 NOT NULL,
    S20_MAALFORM        CHAR(1 CHAR)                                 NOT NULL,
    TK_NR               VARCHAR2(4)                                  NOT NULL,
    F_NR                VARCHAR2(11)                                 NOT NULL,
    OPPRETTET           TIMESTAMP(6)       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_I_KILDE      TIMESTAMP(6)       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    KILDE_IS            VARCHAR2(12 CHAR)  DEFAULT ' '               NOT NULL,
    REGION              CHAR(1 CHAR)       DEFAULT ' '               NOT NULL,
    ID_HEND             NUMBER                                       NOT NULL
        CONSTRAINT PK_SA_HENDELSE
            PRIMARY KEY,
    OPPDATERT           TIMESTAMP(6)       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DB_SPLITT_CONCAT    VARCHAR2(100 CHAR) DEFAULT '99'              NOT NULL
);
